name: ark-shop-db-test

services:
  ark-shop-db-test:
    image: postgres:15
    container_name: ark-shop-db-test-postgres
    env_file: .env.test
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    tmpfs: /var/lib/postgresql/data
