const fs = require('fs');
const path = require('path');

const content = [
  '// Auto-generated by scripts/create-runner.cjs',
  '// Vercel Serverless Function entrypoint (has no src/ counterpart)',
  'const { createApp } = require("./entry");',
  '',
  'let cachedApp;',
  '',
  'module.exports = async (req, res) => {',
  '  if (!cachedApp) {',
  '    try {',
  '      const app = await createApp();',
  '      cachedApp = app.getHttpAdapter().getInstance();',
  '    } catch (err) {',
  '      console.error("FATAL: App initialization failed:", err);',
  '      res.status(500).json({ statusCode: 500, message: "Internal server error" });',
  '      return;',
  '    }',
  '  }',
  '  cachedApp(req, res);',
  '};',
  '',
].join('\n');

const dest = path.join(__dirname, '..', 'dist', 'run.js');
fs.writeFileSync(dest, content);
console.log('Created dist/run.js');
